
// Code generated by file example.go and line 21 DO NOT EDIT.
package example
import (
	"context"
	_ "fmt"
	 "github.com/go-resty/resty/v2"
	 "gitlab.yc345.tv/teacher/golang-base/httperror"
)
func NewUserProviderImpl(r *resty.Client) *UserProviderImpl {
	return &UserProviderImpl{
		r : r,
	}
}

type UserProviderImpl	struct {
	r *resty.Client
}

func (it *UserProviderImpl) GetUser (ctx context.Context,userID string) (User,error) {
	var e httperror.HTTPError
	r := it.r.R().SetError(e)
	
	
	
	
	var ret User
	r = r.SetResult(&ret)
	_, err := r.Get("http://www.baidu.com/id")
	return ret, err
	
}

func (it *UserProviderImpl) PostUser (ctx context.Context,body User) (User,error) {
	var e httperror.HTTPError
	r := it.r.R().SetError(e)
	
	r = r.SetBody(body)
	
	
	var ret User
	r = r.SetResult(&ret)
	_, err := r.Post("http://www.dixincaigang.cn/user/")
	return ret, err
	
}

func (it *UserProviderImpl) DeleteUser (ctx context.Context,userID string) (error) {
	var e httperror.HTTPError
	r := it.r.R().SetError(e)
	
	
	
	
	_, err := r.Delete("http://www.baidu.com/user/:id")
	return err
	
}

func (it *UserProviderImpl) PutUser (ctx context.Context,user User) (User,error) {
	var e httperror.HTTPError
	r := it.r.R().SetError(e)
	
	
	
	
	var ret User
	r = r.SetResult(&ret)
	_, err := r.Put("http://www.baidu.com/user/:id")
	return ret, err
	
}

func (it *UserProviderImpl) PostUser2 (ctx context.Context,headers string,user User) (User,error) {
	var e httperror.HTTPError
	r := it.r.R().SetError(e)
	
	
	
	
	var ret User
	r = r.SetResult(&ret)
	_, err := r.Post("http://www.baidu.com/user2")
	return ret, err
	
}
